os: linux

language: generic

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack
  - $TRAVIS_BUILD_DIR/.stack-work
  timeout: 600

jobs:
  include:

  - env: ARGS=""
    name: "Linux Default"
    # addons: {apt: {packages: [libgmp-dev]}}

  - env: ARGS="--resolver lts-15"
    name: "Linux LTS 15"
    # addons: {apt: {packages: [libgmp-dev]}}

  - env: ARGS="--resolver lts-14 --stack-yaml stack-14.yaml"
    name: "Linux LTS 14"
    # addons: {apt: {packages: [libgmp-dev]}}

  - env: ARGS="--resolver lts-13"
    name: "Linux LTS 13"
    # addons: {apt: {packages: [libgmp-dev]}}

  - env: ARGS="--resolver lts-12"
    name: "Linux LTS 12"
    # addons: {apt: {packages: [libgmp-dev]}}

  - env: ARGS="--resolver lts-11"
    name: "Linux LTS 11"
    # addons: {apt: {packages: [libgmp-dev]}}

  - env: ARGS="--resolver lts-10"
    name: "Linux LTS 10"
    # addons: {apt: {packages: [libgmp-dev]}}

  - env: ARGS="--resolver lts-9"
    name: "Linux LTS 9"
    # addons: {apt: {packages: [libgmp-dev]}}

  - env: ARGS="--resolver nightly"
    name: "Linux Nightly"
    # addons: {apt: {packages: [libgmp-dev]}}

  - env: ARGS=""
    name: "OSX Default"
    os: osx

  - env: ARGS="--resolver lts-15"
    name: "OSX LTS 15"
    os: osx

  - env: ARGS="--resolver lts-14 --stack-yaml stack-14.yaml"
    name: "OSX LTS 14"
    os: osx

  - env: ARGS="--resolver lts-13"
    name: "OSX LTS 13"
    os: osx

  - env: ARGS="--resolver lts-12"
    name: "OSX LTS 12"
    os: osx

  - env: ARGS="--resolver lts-11"
    name: "OSX LTS 11"
    os: osx

  - env: ARGS="--resolver lts-10"
    name: "OSX LTS 10"
    os: osx

  - env: ARGS="--resolver lts-9"
    name: "OSX LTS 9"
    os: osx

  - env: ARGS="--resolver nightly"
    name: "OSX Nightly"
    os: osx

  allow_failures:
  - env: ARGS="--resolver nightly"

before_install:
- |
  set -ex
  # Download and unpack the stack executable
  export PATH=$HOME/.local/bin:$PATH
  mkdir -p ~/.local/bin

  if [ `uname` = "Darwin" ]
  then
    travis_retry curl --insecure -L https://get.haskellstack.org/stable/osx-x86_64.tar.gz | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
  else
    travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  fi
  set +ex

install:
- |
  set -ex
  if [ `uname` -ne "Darwin" ]
  then
    sudo apt-get install -y jq pwgen
  fi
  stack --no-terminal --install-ghc $ARGS test --bench --only-dependencies
  set +ex

script:
- |
  set -ex
  stack --no-terminal $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
  set +ex
