name:                monad-thyme
version:             0.1.0.0
synopsis:            Type class for monads which carry the notion of the current time.
description:         Please see the README on GitHub at <https://github.com/tmortiboy/monad-thyme#readme>
category:            Control
github:              tmortiboy/monad-thyme
homepage:            https://github.com/tmortiboy/monad-thyme
license:             MIT
license-file:        LICENSE
author:              Tom Mortiboy
maintainer:          Tom Mortiboy
copyright:           2020 Tom Mortiboy

extra-source-files:
- README.md
- ChangeLog.md


dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options: -Wall
  dependencies:
  - exceptions
  - mmorph
  - mtl
  - primitive
  - thyme
  - transformers-base

tests:
  monad-thyme-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - monad-thyme
    - mtl
    - QuickCheck
