name:                monad-thyme
version:             0.1.0.0
synopsis:            Type class for monads which carry the notion of the current time.
description:         A MonadTime type class for monads which carry the notion of the current time.
                     The type class has instances for IO and a transformer TimeT which can be used
                     for mocking purposes when testing.
category:            Control, Time
github:              tmortiboy/monad-thyme
homepage:            https://github.com/tmortiboy/monad-thyme
bug-reports:         https://github.com/tmortiboy/monad-thyme/issues
license:             MIT
license-file:        LICENSE
author:              Tom Mortiboy
maintainer:          tom.mortiboy+hackage@gmail.com
copyright:           Copyright (c) 2020 Tom Mortiboy
extra-source-files:  README.md, ChangeLog.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options: -Wall
  dependencies:
  - exceptions
  - mmorph
  - mtl
  - primitive
  - thyme
  - transformers-base

tests:
  monad-thyme-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - monad-thyme
    - mtl
    - QuickCheck
