name:                monad-thyme
version:             0.1.0.0
github:              tmortiboy/monad-thyme
license:             BSD3
author:              Tom Mortiboy
maintainer:          Tom Mortiboy
copyright:           2020 Tom Mortiboy

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/tmortiboy/monad-thyme#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - exceptions
  - mmorph
  - mtl
  - primitive
  - thyme
  - transformers-base

tests:
  monad-thyme-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - monad-thyme
    - mtl
    - QuickCheck
